baseURL: https://k0ral.github.io/
languageCode: en-us
title: My digital garden
subtitle: A non-linear personal web notebook
theme: hugo-geekdoc

params:
  geekdocBreadcrumb: false
  geekdocRepo: "https://github.com/k0ral/k0ral.github.io"
  geekdocBackToTop: false
  geekdocTagsToMenu: true
